name: fluttermodule
description: An embedding Flutter module.

version: 1.0.0+1

environment:
  sdk: ">=2.7.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.alexv525.fluttermodule
    iosBundleIdentifier: com.alexv525.fluttermodule
